# Generated by Django 4.2.5 on 2023-11-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
