# Generated by Django 4.2.5 on 2023-11-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_alter_service_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
