# Generated by Django 4.2.5 on 2023-11-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_service_is_available_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
