# Generated by Django 4.2.5 on 2023-11-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
