# Generated by Django 4.2.5 on 2023-11-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technician',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technician',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
