# Generated by Django 4.2.5 on 2023-11-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_userdetails_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='technician',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
