# Generated by Django 4.2.5 on 2023-11-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_technician_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
