# Generated by Django 4.2.5 on 2023-11-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_userdetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
