# Generated by Django 4.2.5 on 2023-11-07 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0018_alter_service_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop')], max_length=20)),
                ('laptop_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('laptop_model', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_services', models.TextField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_description', models.TextField()),
                ('selected_date', models.DateField()),
                ('selected_time', models.CharField(max_length=20)),
                ('additional_comments', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
