# Generated by Django 4.2.5 on 2023-11-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_alter_service_is_available_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
