# Generated by Django 4.2.5 on 2023-11-22 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0020_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address_choice', models.CharField(max_length=50)),
                ('current_home_address', models.CharField(max_length=255)),
                ('current_city', models.CharField(max_length=100)),
                ('current_pincode', models.CharField(max_length=10)),
                ('new_home_address', models.CharField(max_length=255)),
                ('new_city', models.CharField(max_length=100)),
                ('new_pincode', models.CharField(max_length=10)),
                ('service_type', models.CharField(max_length=50)),
                ('laptop_brand', models.CharField(max_length=50)),
                ('laptop_model', models.CharField(max_length=50)),
                ('selected_services', models.TextField()),
                ('total_service_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('issue_description', models.TextField()),
                ('from_date', models.DateField()),
                ('selected_slot', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
