# Generated by Django 4.2.5 on 2023-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='issue_description',
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_services',
            field=models.CharField(max_length=50),
        ),
    ]
