# Generated by Django 4.2.5 on 2023-11-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_remove_booking_issue_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address_choice',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='current_city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='current_home_address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='current_pincode',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='new_city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='new_home_address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='new_pincode',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.address'),
        ),
    ]
