# Generated by Django 4.2.5 on 2023-11-23 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0023_remove_booking_address_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='address_choice',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='new_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_address', to='root.address'),
        ),
        migrations.AddField(
            model_name='booking',
            name='onsite_service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_mode',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='laptop_brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_services',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_slot',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_service_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
