# Generated by Django 4.2.5 on 2023-11-23 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0024_remove_booking_user_booking_address_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='new_address',
        ),
        migrations.AddField(
            model_name='booking',
            name='new_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='new_home_address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='new_pincode',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
