# Generated by Django 4.2.5 on 2023-11-23 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0026_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Laptop', 'Laptop Service'), ('Desktop', 'Desktop Service')], max_length=20)),
                ('laptop_brand', models.CharField(max_length=20)),
                ('laptop_model', models.CharField(max_length=50)),
                ('selected_services', models.CharField(max_length=255)),
                ('service_mode', models.CharField(choices=[('OnSite', 'On-Site Service'), ('ServiceCenter', 'Service Center')], max_length=20)),
                ('onsite_service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_date', models.DateField()),
                ('selected_slot', models.CharField(max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.address')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.userdetails')),
            ],
        ),
    ]
