# Generated by Django 4.2.5 on 2023-11-24 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0028_technician_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='specialization',
        ),
        migrations.AddField(
            model_name='technician',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.address'),
        ),
    ]
