# Generated by Django 4.2.5 on 2023-11-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0030_laptopbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop')], max_length=7)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('total_service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selected_services', models.ManyToManyField(blank=True, to='root.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
