# Generated by Django 4.2.5 on 2023-12-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0031_booking_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='userdetails',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.userdetails'),
        ),
    ]
