# Generated by Django 4.2.5 on 2024-02-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0033_remove_booking_model_booking_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondHandProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images')),
            ],
        ),
    ]
