# Generated by Django 4.2.5 on 2024-02-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0038_cart_cartproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
