# Generated by Django 4.2.5 on 2024-02-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0040_cart_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondhandproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
