# Generated by Django 4.2.5 on 2024-02-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0041_secondhandproduct_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondhandproduct',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='secondhandproduct',
            name='stock',
        ),
        migrations.AddField(
            model_name='secondhandproduct',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.userdetails'),
        ),
    ]
