# Generated by Django 4.2.5 on 2024-02-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0043_secondhandproduct_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
