# Generated by Django 4.2.5 on 2024-02-29 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0044_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
