# Generated by Django 4.2.5 on 2024-02-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0047_remove_secondhandproduct_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondhandproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.category'),
        ),
    ]
