# Generated by Django 4.2.5 on 2024-03-09 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0052_deliveryboy'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.secondhandproduct')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.userdetails')),
            ],
        ),
    ]
