# Generated by Django 4.2.5 on 2024-03-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0053_wishlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
