# Generated by Django 4.2.5 on 2024-03-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0056_remove_secondhandproduct_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
