# Generated by Django 4.2.5 on 2024-03-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0059_secondhandproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondhandproduct',
            name='is_picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
