# Generated by Django 4.2.5 on 2024-03-14 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0061_remove_payment_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductExchange',
        ),
    ]
