# Generated by Django 4.2.5 on 2024-03-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0063_payment_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='purchase',
        ),
    ]
