# Generated by Django 4.2.5 on 2024-03-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0065_payment_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart',
        ),
    ]
