# Generated by Django 4.2.5 on 2024-03-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0067_payment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
