# Generated by Django 4.2.5 on 2024-03-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0069_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
