# Generated by Django 4.2.5 on 2024-03-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0074_order_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondhandproduct',
            name='delivery_status',
        ),
    ]
