# Generated by Django 4.2.5 on 2024-03-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0075_remove_secondhandproduct_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Out_for_delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='SH', max_length=20),
        ),
    ]
